export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced'

export type PathCategory =
  | 'language'
  | 'programming'
  | 'design'
  | 'business'
  | 'creative'
  | 'science'
  | 'personal'

export type ResourceType = 'video' | 'article' | 'book' | 'podcast' | 'exercise'

export interface PathResource {
  title: string
  type: ResourceType
  url: string
}

export interface LearningPath {
  id: string
  title: string
  description: string
  category: PathCategory
  icon: string
  difficulty: DifficultyLevel
  estimatedHours: number
  tags: string[]
  resources: PathResource[]
}

export const categoryGradients: Record<PathCategory, string> = {
  language: 'from-rose-500/10 to-orange-500/10',
  programming: 'from-emerald-500/10 to-teal-500/10',
  design: 'from-pink-500/10 to-fuchsia-500/10',
  business: 'from-amber-500/10 to-yellow-500/10',
  creative: 'from-cyan-500/10 to-sky-500/10',
  science: 'from-indigo-500/10 to-blue-500/10',
  personal: 'from-lime-500/10 to-green-500/10',
}

export const categoryAccentColors: Record<PathCategory, string> = {
  language: '#f43f5e',
  programming: '#10b981',
  design: '#ec4899',
  business: '#f59e0b',
  creative: '#06b6d4',
  science: '#6366f1',
  personal: '#84cc16',
}

export const learningPaths: LearningPath[] = [
  // ===== LANGUAGE LEARNING =====
  {
    id: 'english-beginner',
    title: 'Learn English (Beginner)',
    description: 'Build a strong foundation in English with essential vocabulary, grammar basics, and everyday conversation skills.',
    category: 'language',
    icon: '🇬🇧',
    difficulty: 'beginner',
    estimatedHours: 120,
    tags: ['English', 'ESL', 'Speaking', 'Grammar'],
    resources: [
      { title: 'English for Beginners - Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=juKd26qkNAw' },
      { title: 'Basic English Grammar Guide', type: 'article', url: 'https://www.englishgrammar.org/' },
      { title: 'English Vocabulary in Use - Elementary', type: 'book', url: 'https://www.cambridge.org/' },
      { title: 'English Made Easy Podcast', type: 'podcast', url: 'https://www.bbc.co.uk/learningenglish' },
      { title: 'Daily Vocabulary Exercises', type: 'exercise', url: 'https://www.duolingo.com/' },
      { title: 'Common Phrases for Beginners', type: 'article', url: 'https://www.phrases.org.uk/' },
    ],
  },
  {
    id: 'english-intermediate',
    title: 'Learn English (Intermediate)',
    description: 'Improve your English fluency with advanced grammar, idiomatic expressions, and professional communication.',
    category: 'language',
    icon: '🇬🇧',
    difficulty: 'intermediate',
    estimatedHours: 150,
    tags: ['English', 'Fluency', 'Idioms', 'Writing'],
    resources: [
      { title: 'Intermediate English Course', type: 'video', url: 'https://www.coursera.org/learn/intermediate-english' },
      { title: 'Mastering English Idioms', type: 'article', url: 'https://www.fluentu.com/blog/english/' },
      { title: 'English Vocabulary in Use - Intermediate', type: 'book', url: 'https://www.cambridge.org/' },
      { title: '6 Minute English - BBC', type: 'podcast', url: 'https://www.bbc.co.uk/programmes/p02pc9xn' },
      { title: 'Write & Improve - Practice Writing', type: 'exercise', url: 'https://writeandimprove.com/' },
      { title: 'TED Talks for English Learners', type: 'video', url: 'https://www.ted.com/' },
    ],
  },
  {
    id: 'english-advanced',
    title: 'Learn English (Advanced)',
    description: 'Perfect your English with nuanced grammar, academic writing, debate skills, and cultural fluency.',
    category: 'language',
    icon: '🇬🇧',
    difficulty: 'advanced',
    estimatedHours: 200,
    tags: ['English', 'Academic', 'Debate', 'Cultural'],
    resources: [
      { title: 'Advanced English Composition', type: 'video', url: 'https://www.coursera.org/' },
      { title: 'The Economist - Advanced Reading', type: 'article', url: 'https://www.economist.com/' },
      { title: 'Advanced Grammar in Use', type: 'book', url: 'https://www.cambridge.org/' },
      { title: 'The Allusionist Podcast', type: 'podcast', url: 'https://www.theallusionist.org/' },
      { title: 'Academic Writing Exercises', type: 'exercise', url: 'https://owl.purdue.edu/' },
      { title: 'Debate and Rhetoric Guide', type: 'article', url: 'https://www.debate.org/' },
    ],
  },
  {
    id: 'spanish',
    title: 'Learn Spanish',
    description: 'Master Spanish from basics to conversation with structured lessons covering grammar, vocabulary, and culture.',
    category: 'language',
    icon: '🇪🇸',
    difficulty: 'beginner',
    estimatedHours: 150,
    tags: ['Spanish', 'Latino', 'Speaking', 'Culture'],
    resources: [
      { title: 'Spanish for Beginners - Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=W6yCRQPBrJ0' },
      { title: 'Spanish Grammar Foundations', type: 'article', url: 'https://www.studyspanish.com/' },
      { title: 'Easy Spanish Step-by-Step', type: 'book', url: 'https://www.mhprofessional.com/' },
      { title: 'Coffee Break Spanish', type: 'podcast', url: 'https://coffeebreaklanguages.com/' },
      { title: 'Spanish Dict - Practice', type: 'exercise', url: 'https://www.spanishdict.com/' },
      { title: 'Spanish Conversation Practice', type: 'video', url: 'https://www.spanishpod101.com/' },
    ],
  },
  {
    id: 'french',
    title: 'Learn French',
    description: 'Discover the beauty of French language with immersive lessons in pronunciation, grammar, and culture.',
    category: 'language',
    icon: '🇫🇷',
    difficulty: 'beginner',
    estimatedHours: 150,
    tags: ['French', 'Francophone', 'Pronunciation', 'Culture'],
    resources: [
      { title: 'French for Beginners Course', type: 'video', url: 'https://www.youtube.com/watch?v=DnKIuMBJXDo' },
      { title: 'French Grammar Essentials', type: 'article', url: 'https://www.francaisfacile.com/' },
      { title: 'French Short Stories for Beginners', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'InnerFrench Podcast', type: 'podcast', url: 'https://innerfrench.com/' },
      { title: 'Kwiziq French Exercises', type: 'exercise', url: 'https://www.kwiziq.com/' },
    ],
  },
  {
    id: 'german',
    title: 'Learn German',
    description: 'Learn German systematically from grammar structures to everyday conversations and professional communication.',
    category: 'language',
    icon: '🇩🇪',
    difficulty: 'beginner',
    estimatedHours: 180,
    tags: ['German', 'Deutsch', 'Grammar', 'Professional'],
    resources: [
      { title: 'German for Beginners - Complete Course', type: 'video', url: 'https://www.youtube.com/watch?v=sR9sS7DnNl4' },
      { title: 'German Grammar Explained', type: 'article', url: 'https://www.deutsch-lernen.com/' },
      { title: 'Momo by Michael Ende', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Coffee Break German', type: 'podcast', url: 'https://coffeebreaklanguages.com/' },
      { title: 'DuoLingo German Practice', type: 'exercise', url: 'https://www.duolingo.com/' },
    ],
  },
  {
    id: 'japanese',
    title: 'Learn Japanese',
    description: 'Dive into Japanese language learning from hiragana/katakana to kanji, grammar, and cultural context.',
    category: 'language',
    icon: '🇯🇵',
    difficulty: 'beginner',
    estimatedHours: 250,
    tags: ['Japanese', 'Kanji', 'Anime', 'Culture'],
    resources: [
      { title: 'Japanese for Beginners', type: 'video', url: 'https://www.youtube.com/watch?v=YKOs8KgIVH4' },
      { title: 'Tae Kim\'s Guide to Japanese Grammar', type: 'article', url: 'https://guidetojapanese.org/learn/' },
      { title: 'Genki I: An Integrated Course', type: 'book', url: 'https://genki.japantimes.co.jp/' },
      { title: 'JapanesePod101', type: 'podcast', url: 'https://www.japanesepod101.com/' },
      { title: 'WaniKani - Kanji Practice', type: 'exercise', url: 'https://www.wanikani.com/' },
      { title: 'Jisho - Online Dictionary', type: 'exercise', url: 'https://jisho.org/' },
    ],
  },
  {
    id: 'korean',
    title: 'Learn Korean',
    description: 'Master Hangul and Korean language from basics through K-drama comprehension and everyday conversations.',
    category: 'language',
    icon: '🇰🇷',
    difficulty: 'beginner',
    estimatedHours: 200,
    tags: ['Korean', 'Hangul', 'K-drama', 'Culture'],
    resources: [
      { title: 'Korean for Beginners Course', type: 'video', url: 'https://www.youtube.com/watch?v=s5x8IjFNrqQ' },
      { title: 'How to Study Korean', type: 'article', url: 'https://www.howtostudykorean.com/' },
      { title: 'Korean Made Simple', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Talk To Me In Korean', type: 'podcast', url: 'https://talktomeinkorean.com/' },
      { title: 'Naver Dictionary Practice', type: 'exercise', url: 'https://learn.dict.naver.com/' },
    ],
  },
  {
    id: 'turkish',
    title: 'Learn Turkish',
    description: 'Explore Turkish language with its unique grammar structure, rich vocabulary, and cultural traditions.',
    category: 'language',
    icon: '🇹🇷',
    difficulty: 'beginner',
    estimatedHours: 160,
    tags: ['Turkish', 'Türkçe', 'Culture', 'Grammar'],
    resources: [
      { title: 'Turkish for Beginners', type: 'video', url: 'https://www.youtube.com/watch?v=1UMFKsFf7NE' },
      { title: 'Turkish Grammar Fundamentals', type: 'article', url: 'https://www.turkishclass.com/' },
      { title: 'Elementary Turkish', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Turkish Tea Time Podcast', type: 'podcast', url: 'https://www.turkishteatime.com/' },
      { title: 'Turkish Language Exercises', type: 'exercise', url: 'https://www.duolingo.com/' },
    ],
  },
  {
    id: 'mandarin',
    title: 'Learn Chinese (Mandarin)',
    description: 'Learn Mandarin Chinese from tones and pinyin to characters, reading, and conversational fluency.',
    category: 'language',
    icon: '🇨🇳',
    difficulty: 'beginner',
    estimatedHours: 280,
    tags: ['Mandarin', 'Chinese', 'Characters', 'Tones'],
    resources: [
      { title: 'Mandarin Chinese for Beginners', type: 'video', url: 'https://www.youtube.com/watch?v=0NJcbyXZPMw' },
      { title: 'Chinese Grammar Wiki', type: 'article', url: 'https://resources.allsetlearning.com/chinese/grammar/' },
      { title: 'Integrated Chinese Level 1', type: 'book', url: 'https://www.cheng-tsui.com/' },
      { title: 'ChinesePod', type: 'podcast', url: 'https://chinesepod.com/' },
      { title: 'Skritter - Character Writing', type: 'exercise', url: 'https://skritter.com/' },
      { title: 'Pleco Dictionary App', type: 'exercise', url: 'https://pleco.com/' },
    ],
  },
  {
    id: 'ielts-prep',
    title: 'IELTS Preparation',
    description: 'Comprehensive IELTS exam preparation covering all four sections: Listening, Reading, Writing, and Speaking.',
    category: 'language',
    icon: '📝',
    difficulty: 'intermediate',
    estimatedHours: 100,
    tags: ['IELTS', 'Exam', 'Academic', 'English'],
    resources: [
      { title: 'IELTS Full Preparation Course', type: 'video', url: 'https://www.youtube.com/watch?v=jCfXbQmjEYk' },
      { title: 'IELTS Writing Task Strategies', type: 'article', url: 'https://www.ielts.org/' },
      { title: 'The Official Cambridge Guide to IELTS', type: 'book', url: 'https://www.cambridge.org/' },
      { title: 'IELTS Energy English Podcast', type: 'podcast', url: 'https://allearsenglish.com/' },
      { title: 'IELTS Practice Tests', type: 'exercise', url: 'https://www.ieltsonlinetests.com/' },
      { title: 'IELTS Speaking Mock Tests', type: 'exercise', url: 'https://www.ielts-speaking.com/' },
    ],
  },
  {
    id: 'toefl-prep',
    title: 'TOEFL Preparation',
    description: 'Prepare for the TOEFL iBT with strategies for reading, listening, speaking, and writing sections.',
    category: 'language',
    icon: '📋',
    difficulty: 'intermediate',
    estimatedHours: 90,
    tags: ['TOEFL', 'Exam', 'Academic', 'English'],
    resources: [
      { title: 'TOEFL iBT Complete Course', type: 'video', url: 'https://www.youtube.com/watch?v=bR_GVHSJPOQ' },
      { title: 'TOEFL Test Prep Strategies', type: 'article', url: 'https://www.ets.org/toefl' },
      { title: 'Official TOEFL iBT Tests', type: 'book', url: 'https://www.ets.org/' },
      { title: 'TOEFL Podcast by Notefull', type: 'podcast', url: 'https://www.notefull.com/' },
      { title: 'TOEFL Practice Online', type: 'exercise', url: 'https://toeflpractice.ets.org/' },
    ],
  },

  // ===== PROGRAMMING & DEVELOPMENT =====
  {
    id: 'python-basics',
    title: 'Python Basics',
    description: 'Start your programming journey with Python — learn variables, data types, loops, functions, and basic OOP.',
    category: 'programming',
    icon: '🐍',
    difficulty: 'beginner',
    estimatedHours: 60,
    tags: ['Python', 'Programming', 'Basics', 'OOP'],
    resources: [
      { title: 'Python for Beginners - Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=rfscVS0vtbw' },
      { title: 'Python.org Official Tutorial', type: 'article', url: 'https://docs.python.org/3/tutorial/' },
      { title: 'Automate the Boring Stuff with Python', type: 'book', url: 'https://automatetheboringstuff.com/' },
      { title: 'Talk Python to Me', type: 'podcast', url: 'https://talkpython.fm/' },
      { title: 'Python Exercises on HackerRank', type: 'exercise', url: 'https://www.hackerrank.com/domains/python' },
      { title: 'Real Python - Beginner Articles', type: 'article', url: 'https://realpython.com/' },
    ],
  },
  {
    id: 'python-web-dev',
    title: 'Python Web Development',
    description: 'Build web applications with Django and Flask — from routing and templates to databases and deployment.',
    category: 'programming',
    icon: '🌐',
    difficulty: 'intermediate',
    estimatedHours: 80,
    tags: ['Python', 'Django', 'Flask', 'Web Dev'],
    resources: [
      { title: 'Django for Beginners - Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=F5mRW0jo-U4' },
      { title: 'Flask Mega-Tutorial', type: 'article', url: 'https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world' },
      { title: 'Two Scoops of Django', type: 'book', url: 'https://www.feldroy.com/' },
      { title: 'Django Chat Podcast', type: 'podcast', url: 'https://djangochat.com/' },
      { title: 'Build a Blog with Django', type: 'exercise', url: 'https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django' },
    ],
  },
  {
    id: 'javascript-fundamentals',
    title: 'JavaScript Fundamentals',
    description: 'Master the building blocks of JavaScript — variables, functions, async programming, DOM manipulation, and ES6+.',
    category: 'programming',
    icon: '⚡',
    difficulty: 'beginner',
    estimatedHours: 70,
    tags: ['JavaScript', 'Web', 'ES6', 'Async'],
    resources: [
      { title: 'JavaScript Full Course for Beginners', type: 'video', url: 'https://www.youtube.com/watch?v=PkZNo7MFNFg' },
      { title: 'MDN JavaScript Guide', type: 'article', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide' },
      { title: 'Eloquent JavaScript', type: 'book', url: 'https://eloquentjavascript.net/' },
      { title: 'JavaScript Jabber', type: 'podcast', url: 'https://javascriptjabber.com/' },
      { title: 'freeCodeCamp JavaScript Challenges', type: 'exercise', url: 'https://www.freecodecamp.org/' },
      { title: 'JavaScript.info - Modern Tutorial', type: 'article', url: 'https://javascript.info/' },
    ],
  },
  {
    id: 'react-development',
    title: 'React Development',
    description: 'Learn React from components and hooks to state management, routing, and building production apps.',
    category: 'programming',
    icon: '⚛️',
    difficulty: 'intermediate',
    estimatedHours: 80,
    tags: ['React', 'Frontend', 'Hooks', 'SPA'],
    resources: [
      { title: 'React Full Course 2024', type: 'video', url: 'https://www.youtube.com/watch?v=bMknfKXIFA8' },
      { title: 'React Official Documentation', type: 'article', url: 'https://react.dev/' },
      { title: 'Learning React (Alex Banks)', type: 'book', url: 'https://www.oreilly.com/' },
      { title: 'React Podcast', type: 'podcast', url: 'https://reactpodcast.com/' },
      { title: 'React Practice Projects', type: 'exercise', url: 'https://reactpractice.dev/' },
    ],
  },
  {
    id: 'nextjs-development',
    title: 'Next.js Development',
    description: 'Master Next.js with App Router, server components, API routes, and full-stack web development.',
    category: 'programming',
    icon: '▲',
    difficulty: 'intermediate',
    estimatedHours: 70,
    tags: ['Next.js', 'React', 'Full-Stack', 'SSR'],
    resources: [
      { title: 'Next.js 14 Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=wm5gMKuwSYk' },
      { title: 'Next.js Official Documentation', type: 'article', url: 'https://nextjs.org/docs' },
      { title: 'Next.js in Action', type: 'book', url: 'https://www.manning.com/' },
      { title: 'Next.js with Vercel Tutorials', type: 'video', url: 'https://vercel.com/learn' },
      { title: 'Build a Full-Stack App', type: 'exercise', url: 'https://nextjs.org/learn' },
    ],
  },
  {
    id: 'typescript-mastery',
    title: 'TypeScript Mastery',
    description: 'Go from JavaScript to TypeScript — types, interfaces, generics, and advanced type patterns.',
    category: 'programming',
    icon: '🔷',
    difficulty: 'intermediate',
    estimatedHours: 60,
    tags: ['TypeScript', 'Types', 'Generics', 'Type Safety'],
    resources: [
      { title: 'TypeScript Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=d56mG7DezGs' },
      { title: 'TypeScript Handbook', type: 'article', url: 'https://www.typescriptlang.org/docs/handbook/' },
      { title: 'Programming TypeScript (Boris Cherny)', type: 'book', url: 'https://www.oreilly.com/' },
      { title: 'TypeScript Exercises', type: 'exercise', url: 'https://www.typescriptlang.org/play' },
      { title: 'Type Challenges', type: 'exercise', url: 'https://github.com/type-challenges/type-challenges' },
    ],
  },
  {
    id: 'nodejs-backend',
    title: 'Node.js Backend Development',
    description: 'Build scalable backend services with Node.js, Express, databases, authentication, and APIs.',
    category: 'programming',
    icon: '🟢',
    difficulty: 'intermediate',
    estimatedHours: 80,
    tags: ['Node.js', 'Express', 'API', 'Backend'],
    resources: [
      { title: 'Node.js Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=Oe421EPjeBE' },
      { title: 'Node.js Best Practices', type: 'article', url: 'https://github.com/goldbergyoni/nodebestpractices' },
      { title: 'Node.js Design Patterns', type: 'book', url: 'https://www.packtpub.com/' },
      { title: 'Node Up Podcast', type: 'podcast', url: 'https://nodeup.com/' },
      { title: 'Build a REST API with Express', type: 'exercise', url: 'https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs' },
    ],
  },
  {
    id: 'rust-programming',
    title: 'Rust Programming',
    description: 'Learn Rust — ownership, borrowing, lifetimes, and building safe, performant systems software.',
    category: 'programming',
    icon: '🦀',
    difficulty: 'advanced',
    estimatedHours: 100,
    tags: ['Rust', 'Systems', 'Memory Safety', 'Performance'],
    resources: [
      { title: 'Rust Programming Tutorial', type: 'video', url: 'https://www.youtube.com/watch?v=BpPEoZW5IiY' },
      { title: 'The Rust Programming Language Book', type: 'book', url: 'https://doc.rust-lang.org/book/' },
      { title: 'Rust by Example', type: 'article', url: 'https://doc.rust-lang.org/rust-by-example/' },
      { title: 'Rustacean Station Podcast', type: 'podcast', url: 'https://rustacean-station.org/' },
      { title: 'Rustlings Exercises', type: 'exercise', url: 'https://github.com/rust-lang/rustlings' },
    ],
  },
  {
    id: 'go-programming',
    title: 'Go Programming',
    description: 'Master Go — goroutines, channels, interfaces, and building concurrent, scalable applications.',
    category: 'programming',
    icon: '🔵',
    difficulty: 'intermediate',
    estimatedHours: 70,
    tags: ['Go', 'Golang', 'Concurrency', 'Backend'],
    resources: [
      { title: 'Go Programming Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=un6ZyFkqFKo' },
      { title: 'A Tour of Go', type: 'article', url: 'https://go.dev/tour/' },
      { title: 'The Go Programming Language', type: 'book', url: 'https://www.gopl.io/' },
      { title: 'Go Time Podcast', type: 'podcast', url: 'https://changelog.com/gotime' },
      { title: 'Go by Example', type: 'exercise', url: 'https://gobyexample.com/' },
      { title: 'Exercism Go Track', type: 'exercise', url: 'https://exercism.org/tracks/go' },
    ],
  },
  {
    id: 'swift-ios',
    title: 'Swift/iOS Development',
    description: 'Build iOS apps with Swift and SwiftUI — from fundamentals to App Store deployment.',
    category: 'programming',
    icon: '🍎',
    difficulty: 'intermediate',
    estimatedHours: 90,
    tags: ['Swift', 'iOS', 'SwiftUI', 'Mobile'],
    resources: [
      { title: 'Swift Programming Tutorial', type: 'video', url: 'https://www.youtube.com/watch?v=comQ1-x2a1Q' },
      { title: 'Swift.org Documentation', type: 'article', url: 'https://www.swift.org/documentation/' },
      { title: 'SwiftUI by Tutorials', type: 'book', url: 'https://www.raywenderlich.com/' },
      { title: 'Swift by Sundell', type: 'podcast', url: 'https://www.swiftbysundell.com/podcast/' },
      { title: 'Apple SwiftUI Tutorials', type: 'exercise', url: 'https://developer.apple.com/tutorials/swiftui' },
    ],
  },
  {
    id: 'kotlin-android',
    title: 'Kotlin/Android Development',
    description: 'Create Android apps with Kotlin and Jetpack Compose — modern mobile development from scratch.',
    category: 'programming',
    icon: '🤖',
    difficulty: 'intermediate',
    estimatedHours: 85,
    tags: ['Kotlin', 'Android', 'Jetpack', 'Mobile'],
    resources: [
      { title: 'Kotlin for Android Course', type: 'video', url: 'https://www.youtube.com/watch?v=F9UC9DY-vIU' },
      { title: 'Kotlin Official Documentation', type: 'article', url: 'https://kotlinlang.org/docs/home.html' },
      { title: 'Kotlin in Action', type: 'book', url: 'https://www.manning.com/' },
      { title: 'Talking Kotlin Podcast', type: 'podcast', url: 'https://talkingkotlin.com/' },
      { title: 'Android Developers Codelabs', type: 'exercise', url: 'https://codelabs.developers.google.com/' },
    ],
  },
  {
    id: 'fullstack-web',
    title: 'Full-Stack Web Development',
    description: 'Become a full-stack developer — frontend, backend, databases, deployment, and real-world project building.',
    category: 'programming',
    icon: '🔗',
    difficulty: 'intermediate',
    estimatedHours: 200,
    tags: ['Full-Stack', 'Frontend', 'Backend', 'DevOps'],
    resources: [
      { title: 'Full-Stack Web Development Bootcamp', type: 'video', url: 'https://www.youtube.com/watch?v=nu_pCVPKzTk' },
      { title: 'The Odin Project', type: 'article', url: 'https://www.theodinproject.com/' },
      { title: 'Full Stack JavaScript (Azat Mardan)', type: 'book', url: 'https://www.apress.com/' },
      { title: 'Full Stack Radio', type: 'podcast', url: 'https://www.fullstackradio.com/' },
      { title: 'Build a Full-Stack App Tutorial', type: 'exercise', url: 'https://www.freecodecamp.org/' },
      { title: 'Deploy with Vercel/Netlify', type: 'article', url: 'https://vercel.com/docs' },
    ],
  },

  // ===== DESIGN =====
  {
    id: 'uiux-fundamentals',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the core principles of user interface and user experience design — wireframing, prototyping, and usability.',
    category: 'design',
    icon: '🎨',
    difficulty: 'beginner',
    estimatedHours: 60,
    tags: ['UI/UX', 'Design', 'Wireframing', 'Usability'],
    resources: [
      { title: 'UI/UX Design Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=K0iUdsjFr4Y' },
      { title: 'Laws of UX', type: 'article', url: 'https://lawsofux.com/' },
      { title: 'Don\'t Make Me Think (Steve Krug)', type: 'book', url: 'https://www.sensible.com/' },
      { title: 'Design Better Podcast', type: 'podcast', url: 'https://www.designbetter.co/podcast' },
      { title: 'UI Design Daily Challenges', type: 'exercise', url: 'https://www.uidesigndaily.com/' },
    ],
  },
  {
    id: 'figma-mastery',
    title: 'Figma Mastery',
    description: 'Become proficient in Figma — components, auto layout, design systems, prototyping, and collaboration.',
    category: 'design',
    icon: '🖌️',
    difficulty: 'intermediate',
    estimatedHours: 50,
    tags: ['Figma', 'Design Tools', 'Prototyping', 'Components'],
    resources: [
      { title: 'Figma UI Design Tutorial', type: 'video', url: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8' },
      { title: 'Figma Official Resources', type: 'article', url: 'https://help.figma.com/' },
      { title: 'Figma for Beginners - YouTube Playlist', type: 'video', url: 'https://www.youtube.com/playlist?list=PLXDU_eVOJTx5LSjOmeBYMevaa2Aas9t0u' },
      { title: 'Design Systems Podcast', type: 'podcast', url: 'https://www.designsystemspodcast.com/' },
      { title: 'Figma Community Files', type: 'exercise', url: 'https://www.figma.com/community' },
    ],
  },
  {
    id: 'graphic-design',
    title: 'Graphic Design Principles',
    description: 'Master the fundamentals of graphic design — typography, color theory, layout, composition, and visual hierarchy.',
    category: 'design',
    icon: '🖼️',
    difficulty: 'beginner',
    estimatedHours: 50,
    tags: ['Graphic Design', 'Typography', 'Color Theory', 'Layout'],
    resources: [
      { title: 'Graphic Design Fundamentals', type: 'video', url: 'https://www.youtube.com/watch?v=YqQxWOPnr6M' },
      { title: 'The Principles of Design', type: 'article', url: 'https://www.interaction-design.org/' },
      { title: 'Thinking with Type', type: 'book', url: 'https://thinkingwithtype.com/' },
      { title: 'The Deeply Graphic Design Podcast', type: 'podcast', url: 'https://www.designomark.com/' },
      { title: 'Daily Logo Challenge', type: 'exercise', url: 'https://dailylearn.design/' },
    ],
  },
  {
    id: 'motion-design',
    title: 'Motion Design',
    description: 'Learn motion design principles — animation timing, easing, transitions, and creating engaging UI animations.',
    category: 'design',
    icon: '✨',
    difficulty: 'intermediate',
    estimatedHours: 60,
    tags: ['Motion', 'Animation', 'UI Animation', 'After Effects'],
    resources: [
      { title: 'Motion Design Principles Course', type: 'video', url: 'https://www.youtube.com/watch?v=uY6wKkiOzMg' },
      { title: '12 Principles of Animation', type: 'article', url: 'https://www.creativebloq.com/' },
      { title: 'The Animators Survival Kit', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Motion Design School Tutorials', type: 'video', url: 'https://motiondesign.school/' },
      { title: 'CSS Animation Exercises', type: 'exercise', url: 'https://animista.net/' },
    ],
  },

  // ===== BUSINESS & CAREER =====
  {
    id: 'project-management',
    title: 'Project Management (PMP)',
    description: 'Prepare for project management certification — methodologies, risk management, stakeholder communication, and Agile.',
    category: 'business',
    icon: '📋',
    difficulty: 'intermediate',
    estimatedHours: 80,
    tags: ['PMP', 'Agile', 'Management', 'Leadership'],
    resources: [
      { title: 'PMP Certification Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=GC7pN8Mjot8' },
      { title: 'PMI Official Resources', type: 'article', url: 'https://www.pmi.org/' },
      { title: 'PMBOK Guide 7th Edition', type: 'book', url: 'https://www.pmi.org/pmbok-guide-standards' },
      { title: 'Project Management Podcast', type: 'podcast', url: 'https://www.project-management-podcast.com/' },
      { title: 'PMP Practice Exams', type: 'exercise', url: 'https://www.pmtraining.com/' },
    ],
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    description: 'Learn digital marketing — SEO, social media, content marketing, email campaigns, and analytics.',
    category: 'business',
    icon: '📢',
    difficulty: 'beginner',
    estimatedHours: 60,
    tags: ['Marketing', 'SEO', 'Social Media', 'Analytics'],
    resources: [
      { title: 'Digital Marketing Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=nU-IIXBWlS4' },
      { title: 'Google Digital Garage', type: 'article', url: 'https://learndigital.withgoogle.com/digitalgarage' },
      { title: 'Digital Marketing for Dummies', type: 'book', url: 'https://www.wiley.com/' },
      { title: 'Marketing Over Coffee', type: 'podcast', url: 'https://www.marketingovercoffee.com/' },
      { title: 'Google Analytics Practice', type: 'exercise', url: 'https://analytics.google.com/' },
    ],
  },
  {
    id: 'entrepreneurship',
    title: 'Entrepreneurship 101',
    description: 'Launch your entrepreneurial journey — ideation, validation, business models, funding, and scaling.',
    category: 'business',
    icon: '🚀',
    difficulty: 'intermediate',
    estimatedHours: 50,
    tags: ['Startup', 'Business', 'Innovation', 'Funding'],
    resources: [
      { title: 'Entrepreneurship Masterclass', type: 'video', url: 'https://www.youtube.com/watch?v=5pLE6uqF3Rs' },
      { title: 'Y Combinator Startup School', type: 'article', url: 'https://www.startupschool.org/' },
      { title: 'The Lean Startup (Eric Ries)', type: 'book', url: 'https://theleanstartup.com/' },
      { title: 'How I Built This Podcast', type: 'podcast', url: 'https://www.npr.org/podcasts/510313/how-i-built-this' },
      { title: 'Business Model Canvas Practice', type: 'exercise', url: 'https://www.strategyzer.com/canvas' },
    ],
  },
  {
    id: 'public-speaking',
    title: 'Public Speaking',
    description: 'Overcome stage fright and become a confident speaker — structure, delivery, persuasion, and presence.',
    category: 'business',
    icon: '🎤',
    difficulty: 'beginner',
    estimatedHours: 30,
    tags: ['Speaking', 'Communication', 'Presentation', 'Confidence'],
    resources: [
      { title: 'Public Speaking Masterclass', type: 'video', url: 'https://www.youtube.com/watch?v=H1E0OzfajCE' },
      { title: 'Toastmasters International Resources', type: 'article', url: 'https://www.toastmasters.org/' },
      { title: 'Talk Like TED (Carmine Gallo)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'The Public Speaker Podcast', type: 'podcast', url: 'https://www.quickanddirtytips.com/public-speaker/' },
      { title: 'Record & Review Your Speeches', type: 'exercise', url: 'https://www.toastmasters.org/' },
    ],
  },
  {
    id: 'financial-literacy',
    title: 'Financial Literacy',
    description: 'Build financial knowledge — budgeting, investing, compound interest, retirement planning, and wealth building.',
    category: 'business',
    icon: '💰',
    difficulty: 'beginner',
    estimatedHours: 40,
    tags: ['Finance', 'Investing', 'Budgeting', 'Wealth'],
    resources: [
      { title: 'Financial Literacy Course', type: 'video', url: 'https://www.youtube.com/watch?v=4LlVhm2SsTc' },
      { title: 'Investopedia - Learn the Basics', type: 'article', url: 'https://www.investopedia.com/' },
      { title: 'Rich Dad Poor Dad (Robert Kiyosaki)', type: 'book', url: 'https://www.richdad.com/' },
      { title: 'Planet Money Podcast', type: 'podcast', url: 'https://www.npr.org/sections/money/' },
      { title: 'Budget Planning Worksheet', type: 'exercise', url: 'https://www.nerdwallet.com/' },
    ],
  },
  {
    id: 'leadership',
    title: 'Leadership Skills',
    description: 'Develop leadership capabilities — team management, decision making, emotional intelligence, and strategic thinking.',
    category: 'business',
    icon: '👑',
    difficulty: 'intermediate',
    estimatedHours: 45,
    tags: ['Leadership', 'Management', 'Strategy', 'Teams'],
    resources: [
      { title: 'Leadership Principles Course', type: 'video', url: 'https://www.coursera.org/learn/leadership' },
      { title: 'Harvard Business Review - Leadership', type: 'article', url: 'https://hbr.org/topic/leadership' },
      { title: 'The 5 Levels of Leadership (John Maxwell)', type: 'book', url: 'https://www.johnmaxwell.com/' },
      { title: 'HBR IdeaCast', type: 'podcast', url: 'https://hbr.org/podcasts/ideacast' },
      { title: 'Leadership Self-Assessment', type: 'exercise', url: 'https://www.mindtools.com/' },
    ],
  },

  // ===== CREATIVE =====
  {
    id: 'creative-writing',
    title: 'Creative Writing',
    description: 'Unlock your creative writing potential — fiction, poetry, storytelling techniques, and finding your voice.',
    category: 'creative',
    icon: '✍️',
    difficulty: 'beginner',
    estimatedHours: 50,
    tags: ['Writing', 'Fiction', 'Storytelling', 'Creativity'],
    resources: [
      { title: 'Creative Writing Course', type: 'video', url: 'https://www.youtube.com/watch?v=1qUT9JMqH1k' },
      { title: 'Writer\'s Digest Articles', type: 'article', url: 'https://www.writersdigest.com/' },
      { title: 'On Writing (Stephen King)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Writing Excuses Podcast', type: 'podcast', url: 'https://writingexcuses.com/' },
      { title: 'NaNoWriMo Writing Challenge', type: 'exercise', url: 'https://nanowrimo.org/' },
      { title: 'Daily Writing Prompts', type: 'exercise', url: 'https://www.reddit.com/r/WritingPrompts/' },
    ],
  },
  {
    id: 'photography',
    title: 'Photography Fundamentals',
    description: 'Learn photography from the ground up — composition, lighting, camera settings, and post-processing.',
    category: 'creative',
    icon: '📷',
    difficulty: 'beginner',
    estimatedHours: 40,
    tags: ['Photography', 'Composition', 'Lighting', 'Post-Processing'],
    resources: [
      { title: 'Photography for Beginners Course', type: 'video', url: 'https://www.youtube.com/watch?v=S2lNImKSq64' },
      { title: 'Digital Photography School', type: 'article', url: 'https://digital-photography-school.com/' },
      { title: 'Understanding Exposure (Bryan Peterson)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Criminal Photography Podcast', type: 'podcast', url: 'https://photographyconcentrate.com/' },
      { title: 'Daily Photo Challenge', type: 'exercise', url: 'https://365project.org/' },
    ],
  },
  {
    id: 'music-production',
    title: 'Music Production',
    description: 'Start producing music — DAWs, mixing, mastering, sound design, and creating your own tracks.',
    category: 'creative',
    icon: '🎵',
    difficulty: 'beginner',
    estimatedHours: 80,
    tags: ['Music', 'Production', 'Mixing', 'DAW'],
    resources: [
      { title: 'Music Production for Beginners', type: 'video', url: 'https://www.youtube.com/watch?v=6SgmmzBUMaw' },
      { title: 'SoundOnSound - Production Articles', type: 'article', url: 'https://www.soundonsound.com/' },
      { title: 'Dance Music Manual (Rick Snoman)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Pensado\'s Place Podcast', type: 'podcast', url: 'https://pensadosplace.tv/' },
      { title: 'Ableton Learning Music', type: 'exercise', url: 'https://learningmusic.ableton.com/' },
    ],
  },
  {
    id: 'video-editing',
    title: 'Video Editing',
    description: 'Learn video editing — cutting, transitions, color grading, effects, and storytelling through editing.',
    category: 'creative',
    icon: '🎬',
    difficulty: 'beginner',
    estimatedHours: 50,
    tags: ['Video', 'Editing', 'Premiere', 'Color Grading'],
    resources: [
      { title: 'Video Editing Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=O4xZ6qK8DA8' },
      { title: 'Adobe Premiere Pro Tutorials', type: 'article', url: 'https://helpx.adobe.com/premiere-pro/tutorials.html' },
      { title: 'In the Blink of an Eye (Walter Murch)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'The Edit Podcast', type: 'podcast', url: 'https://www.provideocoalition.com/' },
      { title: 'Edit a Short Film Project', type: 'exercise', url: 'https://www.skillshare.com/' },
    ],
  },

  // ===== SCIENCE & MATH =====
  {
    id: 'calculus',
    title: 'Calculus Fundamentals',
    description: 'Understand calculus from limits and derivatives to integrals and multivariable calculus applications.',
    category: 'science',
    icon: '📐',
    difficulty: 'intermediate',
    estimatedHours: 80,
    tags: ['Calculus', 'Math', 'Derivatives', 'Integrals'],
    resources: [
      { title: 'Calculus Full Course (3Blue1Brown)', type: 'video', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr' },
      { title: 'Khan Academy - Calculus', type: 'article', url: 'https://www.khanacademy.org/math/calculus-1' },
      { title: 'Calculus: Early Transcendentals (Stewart)', type: 'book', url: 'https://www.cengage.com/' },
      { title: 'Math Ed Podcast', type: 'podcast', url: 'https://www.nctm.org/' },
      { title: 'Calculus Practice Problems', type: 'exercise', url: 'https://www.symbolab.com/' },
    ],
  },
  {
    id: 'statistics',
    title: 'Statistics & Probability',
    description: 'Master statistics and probability — distributions, hypothesis testing, regression, and Bayesian thinking.',
    category: 'science',
    icon: '🎲',
    difficulty: 'intermediate',
    estimatedHours: 70,
    tags: ['Statistics', 'Probability', 'Data', 'Bayesian'],
    resources: [
      { title: 'Statistics Course (Khan Academy)', type: 'video', url: 'https://www.khanacademy.org/math/statistics-probability' },
      { title: 'StatTrek - Statistics Tutorial', type: 'article', url: 'https://stattrek.com/' },
      { title: 'Think Stats (Allen Downey)', type: 'book', url: 'https://greenteapress.com/thinkstats/' },
      { title: 'More or Less Podcast (BBC)', type: 'podcast', url: 'https://www.bbc.co.uk/programmes/p02nrss1' },
      { title: 'Statistical Exercises', type: 'exercise', url: 'https://www.kaggle.com/learn/statistics' },
    ],
  },
  {
    id: 'physics',
    title: 'Physics Essentials',
    description: 'Explore fundamental physics — mechanics, thermodynamics, electromagnetism, and modern physics concepts.',
    category: 'science',
    icon: '🔭',
    difficulty: 'intermediate',
    estimatedHours: 100,
    tags: ['Physics', 'Mechanics', 'Electromagnetism', 'Science'],
    resources: [
      { title: 'Physics Full Course', type: 'video', url: 'https://www.youtube.com/watch?v=KykwL9Y7qIM' },
      { title: 'The Physics Classroom', type: 'article', url: 'https://www.physicsclassroom.com/' },
      { title: 'Feynman Lectures on Physics', type: 'book', url: 'https://www.feynmanlectures.caltech.edu/' },
      { title: 'Physics World Podcast', type: 'podcast', url: 'https://physicsworld.com/podcasts/' },
      { title: 'PhET Simulations', type: 'exercise', url: 'https://phet.colorado.edu/' },
    ],
  },
  {
    id: 'astronomy',
    title: 'Astronomy',
    description: 'Journey through the cosmos — planets, stars, galaxies, cosmology, and the latest space discoveries.',
    category: 'science',
    icon: '🌌',
    difficulty: 'beginner',
    estimatedHours: 40,
    tags: ['Astronomy', 'Space', 'Cosmology', 'Stars'],
    resources: [
      { title: 'Astronomy 101 Course', type: 'video', url: 'https://www.youtube.com/watch?v=YNX5klFhDLM' },
      { title: 'NASA - Solar System Exploration', type: 'article', url: 'https://solarsystem.nasa.gov/' },
      { title: 'Cosmos (Carl Sagan)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Astronomy Cast Podcast', type: 'podcast', url: 'https://www.astronomycast.com/' },
      { title: 'Stargazing Practice Guide', type: 'exercise', url: 'https://stellarium-web.org/' },
    ],
  },

  // ===== PERSONAL DEVELOPMENT =====
  {
    id: 'speed-reading',
    title: 'Speed Reading',
    description: 'Learn to read faster with better comprehension — techniques, exercises, and building reading habits.',
    category: 'personal',
    icon: '📖',
    difficulty: 'beginner',
    estimatedHours: 20,
    tags: ['Reading', 'Speed', 'Comprehension', 'Habits'],
    resources: [
      { title: 'Speed Reading Techniques', type: 'video', url: 'https://www.youtube.com/watch?v=jeI2MIeF-Qk' },
      { title: 'How to Read Faster', type: 'article', url: 'https://www.spreeder.com/' },
      { title: 'Breakthrough Rapid Reading (Peter Kump)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Speed Reading Practice Tool', type: 'exercise', url: 'https://www.spreeder.com/app.php' },
      { title: 'Reading Comprehension Tests', type: 'exercise', url: 'https://www.readingsoft.com/' },
    ],
  },
  {
    id: 'memory-techniques',
    title: 'Memory Techniques',
    description: 'Improve your memory — mnemonic devices, memory palaces, spaced repetition, and cognitive strategies.',
    category: 'personal',
    icon: '🧩',
    difficulty: 'beginner',
    estimatedHours: 25,
    tags: ['Memory', 'Mnemonics', 'Learning', 'Cognitive'],
    resources: [
      { title: 'Memory Improvement Course', type: 'video', url: 'https://www.youtube.com/watch?v=kO0J3b3iFKc' },
      { title: 'Art of Memory - Techniques', type: 'article', url: 'https://artofmemory.com/' },
      { title: 'Moonwalking with Einstein (Joshua Foer)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Anki - Spaced Repetition', type: 'exercise', url: 'https://apps.ankiweb.net/' },
      { title: 'Memory Palace Building', type: 'exercise', url: 'https://artofmemory.com/wiki/How_to_Build_a_Memory_Palace' },
    ],
  },
  {
    id: 'critical-thinking',
    title: 'Critical Thinking',
    description: 'Sharpen your analytical mind — logical reasoning, argument analysis, cognitive biases, and decision making.',
    category: 'personal',
    icon: '💡',
    difficulty: 'intermediate',
    estimatedHours: 30,
    tags: ['Critical Thinking', 'Logic', 'Reasoning', 'Decision'],
    resources: [
      { title: 'Critical Thinking Course', type: 'video', url: 'https://www.youtube.com/watch?v=dItugn16eWQ' },
      { title: 'Your Bias List - Cognitive Biases', type: 'article', url: 'https://yourbias.is/' },
      { title: 'Thinking, Fast and Slow (Daniel Kahneman)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'Rationally Speaking Podcast', type: 'podcast', url: 'https://rationallyspeakingpodcast.org/' },
      { title: 'Logical Fallacy Exercises', type: 'exercise', url: 'https://yourlogicalfallacyis.com/' },
    ],
  },
  {
    id: 'emotional-intelligence',
    title: 'Emotional Intelligence',
    description: 'Develop EQ — self-awareness, empathy, social skills, emotion regulation, and relationship management.',
    category: 'personal',
    icon: '❤️',
    difficulty: 'beginner',
    estimatedHours: 30,
    tags: ['EQ', 'Emotions', 'Empathy', 'Self-Awareness'],
    resources: [
      { title: 'Emotional Intelligence Course', type: 'video', url: 'https://www.youtube.com/watch?v=YCcwRZOnEtM' },
      { title: '6 Seconds EQ Resources', type: 'article', url: 'https://www.6seconds.org/' },
      { title: 'Emotional Intelligence 2.0 (Travis Bradberry)', type: 'book', url: 'https://www.amazon.com/' },
      { title: 'The Emotional Intelligence Podcast', type: 'podcast', url: 'https://www.eq.org/' },
      { title: 'EQ Self-Assessment', type: 'exercise', url: 'https://www.berkeley.edu/' },
    ],
  },
]

export const categoryKeys: PathCategory[] = [
  'language', 'programming', 'design', 'business', 'creative', 'science', 'personal',
]

export function getPathsByCategory(category: PathCategory): LearningPath[] {
  return learningPaths.filter(p => p.category === category)
}

export function searchPaths(query: string): LearningPath[] {
  const lowerQuery = query.toLowerCase()
  return learningPaths.filter(p =>
    p.title.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  )
}
